### ISSUE TITLE
Images in text are ingested but incorrectly referenced

### ISSUE THREAD

**Issue by scottnelle** [alleyinteractive/feed-consumer#50]
### Description of the bug

When an RSS item with an inline image is ingested, the image is downloaded to the media library and then placed in the post content like this:

```HTML
<!-- wp:image -->
<figure class="wp-block-image"><img src="http://226565" alt=""/></figure>
<!-- /wp:image -->
```
Where 226565 is the attachment ID of the image. It seems like there's a step missing to get the attachment image src.

### Steps To Reproduce

Ingest an RSS item with an image in the content
View the item in the editor or on the front end of the site.

**Comment by srtfisher** [comment]
Fixed via https://github.com/alleyinteractive/wp-block-converter/pull/9
